### PR TITLE
Throttle request rate

### PR DESCRIPTION
**Pull request by lifeBCE**
Added ability to throttle request rate through each connection. If throttle is set to 10 requests per second and pool size is set to 10 connections then 100 requests per second would be allowed.

Also added #checked_out to give visibility into pool utilization from application space.

### CODE REVIEW

**Comment by bpardee** [comment]
Hi Eric, thanks for the pull request.  I just have a couple of questions.  I was curious about the use case for this?  Also, why throttle existing connections but not new connections?  When throttling, it seems like it would be going into a pretty cpu intensive loop while it waits for the throttling delay?

**Comment by lifeBCE** [comment]
Hey Brad,

My particular use case is a RESTFul API that allows a certain request rate which is pretty common these days. Most RESTFul APIs want the user to use persistent connections with a certain limit on requests per second per connection.

I only added this logic to throttle existing connections because my thinking was that a new connection will only be a new connection when it is first created and first used. After it is checked in from its first usage, it becomes an existing connection. It is that reuse of existing connections that needs throttling.

Lastly, I agree that the nullifying of the connection and allowing the until loop to be the blocker may spike CPU but only if the delta is large since there is some meat in the loop (connections - checked out and sort). Could call a `@condition.wait(interval - (1.0 / @throttle))` to prevent this instead of just nullifying `connection`.

**Comment by bpardee** [comment]
Hi Eric, sorry to not be responsive.  Having one of those weeks!

Could you add the condition.wait like you suggested?  Also, I would like to keep the examples as simple as possible with the very common options so could you remove throttle from the README.md example but add it to the GenePool#initialize documentation?

Thanks!

**Comment by lifeBCE** [comment]
Made the updates but used a sleep instead of `@condition.wait`. The monitor wait call releases the lock while waiting allowing other threads to process which was causing a race condition on stale connections. All Travis tests are passing except in jruby. Not sure why this would not throttle correctly in jruby but maybe because jruby has true concurrency?

**Comment by lifeBCE** [comment]
Heh, seems jruby is just too fast! Updated unit test to assert delta is greater than **or equal to** allowed interval. Before it was just greater than and jruby was too fast so failed because it was exactly equal.

**Comment by reidmorrison** [comment]
Conceptually I like the idea of throttling either each connection, or even the entire
connection pool based on usage rates.

This particular use-case of throttling the number of times a connection is used over a time
interval could be useful to others. In general however, IT Administrators are more likely to 
implement rate limiting at a firewall based on source ip address rather than by connection.
Although, by connection is still useful.
Source IP address throttling is far more likely since it would be trivial to exceed the requests
per second by just creating a new connection and using that one until the over-used connection
can be used again.

Currently the connection pool implements throttling based on duration rather than throughput.
It is achieved by limiting the number of connections in the pool.

In order to throttle based on connection usage each connection will need to keep a count of the number
of times it has been used over a specific time-period. It could be x requests per second, or
even y requests per 5 minute interval.

Looking at this proposed solution it assumes that every call takes exactly the same amount of time,
which in general is not very likely. In this particular use-case the calls may be similar, but
the solution will need to handle requests where some calls take longer than others.

For example, 80% of calls may take 0.01s to complete, and then 20% take 0.1s to complete.
The connections where calls are taking longer will be under-utilized. Making each connection calculate
it's actual rate would result in greater throughput. 

There is also a call to `sleep` if a particular connection is re-used too quickly. This should
be replaced with a mechanism that returns "no connections available", so that a new connection
can be created and used immediately instead of just sleeping the current thread. This would
continue until the max pool size limit is reached.

Implementing a mechanism where each connection calculates its actual usage rate could be
fairly complex though. Additionally, the solution should support plug-able algorithms
for determining if a connection is available for use. This plug-able approach would allow
the Rate based algorithm to be added to a pool without affecting the performance of
existing pools that do not use rate limiting.       

The first step is to implement logic where each connection calculates its actual rate, and
then allow the checkout process to skip these "un-available" connections.

**Comment by lifeBCE** [comment]
I don't necessarily disagree with anything you have said but I do believe your analysis of this proposed solution is a bit off. It merely prevents any single connection from exceeding a configurable rate by sorting on last used and checking interval. It is not to maximize throughput but to limit throughput. It also does not limit the number of connections in any way. The pool size is what has and still limits the number of connections. If a request comes in for a connection when one is not available and there is room left in the pool, a new one is created.

I do agree that the pool should be exhausted prior to throttling so that could be interesting though I suspect it would require a somewhat largish rewrite of `#checkout`. Your expressed preference, in its entirety, would require a complete rewrite of the gem which is currently only 322 lines including comments. Not to say that your idea does not sound useful but that maybe creating your own gem would be a better route?

I look forward to whatever you choose, keep us updated.

**Pull request closed without merging**
